version: '3.8'

services:

  db:
    image: mariadb:10.6
    container_name: school-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=database1
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "5001:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: school-phpmyadmin
    restart: unless-stopped
    ports:
      - "5002:80"
    environment:
      - PMA_HOST=db\